### ISSUE TITLE
Change date format to a 24-hour clock

### ISSUE THREAD

**Issue by kncp** [facilio-team/communication#6]
ここです 🙏 
<img width="594" alt="2018-07-31 13 31 48" src="https://user-images.githubusercontent.com/29544113/43437862-21f689fa-94c6-11e8-9616-5600392b1f06.png">

**Comment by numa08** [comment]
開催日時の設定を 16:00 にしても表記上は 04:00 になっちゃう問題があります。

**Comment by mironal** [comment]
ご報告ありがとうございます. 近日中に修正いたします.

**Comment by mironal** [comment]
こちらの不具合修正いたしました。 次のリリースをお待ち下さい

**Comment by mironal** [comment]
fix v1.1.0
