### ISSUE TITLE
Opening document is slow

### ISSUE THREAD

**Issue by numa08** [facilio-team/communication#7]
covelline/facilio#779

ときどきアクセスが遅いときがあるので、そのときの Timeline 情報を貼り付けて行きます

**Comment by nakaryo** [comment]
2018/8/6 17:20 頃にチームトップのURLにアクセス。
![2018_0806_1720_1](https://user-images.githubusercontent.com/22660224/43705926-deb78ddc-999e-11e8-861b-c96f9e252a0d.png)

初期描画が遅いなと感じた部分は、認証が行われる際の名前解決に時間が掛かっているようでした。

**Comment by takkumattsu** [comment]
@nakaryo 連絡ありがとうございます！
どうやら @nakaryo さんの環境のみでおきている問題でfacilio本体の問題ではないことがわかった。
